### ISSUE TITLE
Can you do the same with doc88.com

### ISSUE THREAD

**Issue by VanjaSt** [dearplain/douding#3]
Can you do the same with doc88.com, at example:

http://www.doc88.com/p-3167601006923.html

**Comment by dearplain** [comment]
OK, I try.

**Comment by VanjaSt** [comment]
Thanks in advance!

**Comment by VanjaSt** [comment]
If this can be helpfull: Jus a detail: when scroll documet to the end it stops on page 5 and to proceed to the rest of document must press arrow "next" and after that you can scroll to the end of document...

**Comment by dearplain** [comment]
Failed, close it.
